user#signup:
  desc: User signup
  path: /signup

user#create:
  desc: User create
  path: /create
  method: post

user#login:
  desc: User login
  path: /login

user#session:
  desc: User session
  path: /session
  method: post

user#logout:
  desc: User logout
  path: /logout

user#settings:
  desc: User settings
  path: /settings
  filters:
    - require_user_login

user#update:
  desc: User update
  path: /update
  method: put
  filters:
    - require_user_login

user#password:
  desc: User password
  path: /password
  method: put
  filters:
    - require_user_login

